services:
  dagster:
    image: dagster-docker-pipeline:latest
    command: dagit -h 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  dagster-daemon:
    image: dagster-docker-pipeline:latest
    command: dagster-daemon run
    depends_on:
      - dagster
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: dagster
      POSTGRES_PASSWORD: dagster
      POSTGRES_DB: dagster
    ports:
      - "5432:5432"
